//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelBills.Prism.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelBills.Prism.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address..
        /// </summary>
        public static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address....
        /// </summary>
        public static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Value.
        /// </summary>
        public static string BillValue {
            get {
                return ResourceManager.GetString("BillValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password .
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the city.
        /// </summary>
        public static string CityPlaceHolder {
            get {
                return ResourceManager.GetString("CityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a confirmation for new password.
        /// </summary>
        public static string ConfirmNewPasswordError {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation and the new password does not match.
        /// </summary>
        public static string ConfirmNewPasswordError2 {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirmation.
        /// </summary>
        public static string ConfirmNewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your current password.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password .
        /// </summary>
        public static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a document..
        /// </summary>
        public static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your document number....
        /// </summary>
        public static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email..
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name..
        /// </summary>
        public static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Camera .
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        public static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password incorrect.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Main_Page {
            get {
                return ResourceManager.GetString("Main Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string Modify_user {
            get {
                return ResourceManager.GetString("Modify user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password.
        /// </summary>
        public static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new password.
        /// </summary>
        public static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trip Page.
        /// </summary>
        public static string NewTripPage {
            get {
                return ResourceManager.GetString("NewTripPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        public static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        public static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        public static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least 6 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recover.
        /// </summary>
        public static string PasswordRecover {
            get {
                return ResourceManager.GetString("PasswordRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone....
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Source.
        /// </summary>
        public static string PictureSource {
            get {
                return ResourceManager.GetString("PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a city.
        /// </summary>
        public static string PleaseEnterACity {
            get {
                return ResourceManager.GetString("PleaseEnterACity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the bill value.
        /// </summary>
        public static string PleaseEnterTheBillValue {
            get {
                return ResourceManager.GetString("PleaseEnterTheBillValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please grant the required permissions.
        /// </summary>
        public static string PleaseGrantTheRequiredRermissions {
            get {
                return ResourceManager.GetString("PleaseGrantTheRequiredRermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a trip type!.
        /// </summary>
        public static string PleaseSelectATripType {
            get {
                return ResourceManager.GetString("PleaseSelectATripType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the trip expense type.
        /// </summary>
        public static string PleaseSelectTheTripExpenseType {
            get {
                return ResourceManager.GetString("PleaseSelectTheTripExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a picture of the bill.
        /// </summary>
        public static string PleaseUploadAPictureOfTheBill {
            get {
                return ResourceManager.GetString("PleaseUploadAPictureOfTheBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the trip expense type.
        /// </summary>
        public static string SelectTheTripExpenseType {
            get {
                return ResourceManager.GetString("SelectTheTripExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the trip type.
        /// </summary>
        public static string SelectTheTripType {
            get {
                return ResourceManager.GetString("SelectTheTripType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date .
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the image to add a new image.
        /// </summary>
        public static string TapTheImage {
            get {
                return ResourceManager.GetString("TapTheImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the trip to add a new expense.
        /// </summary>
        public static string TapTheTrip {
            get {
                return ResourceManager.GetString("TapTheTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date must be less than the end date.
        /// </summary>
        public static string TheStartDateMustBeLess {
            get {
                return ResourceManager.GetString("TheStartDateMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Expense type.
        /// </summary>
        public static string TripExpenseType {
            get {
                return ResourceManager.GetString("TripExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips Page.
        /// </summary>
        public static string TripsPage {
            get {
                return ResourceManager.GetString("TripsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Type .
        /// </summary>
        public static string TripType {
            get {
                return ResourceManager.GetString("TripType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Types .
        /// </summary>
        public static string TripTypes {
            get {
                return ResourceManager.GetString("TripTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was updated successfully.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Welcome to my application in which you can login to register the trips you make and their respective expenses, I hope you enjoy it.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
